name: CI/CD-HML
on:
  workflow_dispatch:
  push:
    branches: dev01
jobs:   
  mergedev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: getreleaseid  
        run: |
          release=$(curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/hirata11/reactstatic/pulls \
            -d '{"title":"An automatically created PR!","body":"Update branch to reflect new version changes","head":"dev01","base":"dev02"}' | jq '.number')
          echo $release

          #release=$(curl \
            #-X POST \
            #-H "Accept: application/vnd.github+json" \
            #-H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            #https://api.github.com/repos/hirata11/reactstatic/pulls \
            #-d '{"title":"An automatically created PR!","body":"Update branch to reflect new version changes","head":"dev02","base":"dev01"}')
          #echo $release

          curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            https://api.github.com/repos/hirata11/reactstatic/pulls/$release/merge \
            -d '{"commit_title":"An automatically merge","commit_message":"Merge dev01 to dev02"}'


        shell: bash
